### ISSUE TITLE
Requirements. txt needs version information

### ISSUE THREAD

**Issue by gits00** [iml130/nncg#1]
This is very interesting work but I am not able to get this running with Tensor flow 2.5 and Kera 2.5.0.dev2021032900. Is their a combination of TF and Keras that works with nncg? I have installed python 3.7 and clang 6.
Thanks,
-gits

**Comment by OliverUrbann** [comment]
As I expected some things have changed. I fixed that so TF 2.5 can (and must) be used. Probably a bit older or newer versions will also work but I set the tf version in the requirements.txt to 2.5. Please test if that works for you.

**Comment by gits00** [comment]
Tried the new "requirements.txt". It went well till "compile.py" step this time.   

python3 applications/daimler/compile.py
Adding CNN nodes to graph |----------------------------------------| 0.0% Unknown layer

Not sure if this message of "Unknown layer" was expected.

Don't see the "cnn_gen.cpp" file created either. But I see a new file - "./examples/daimler.c"

compiling daimler.c using clang (clang version 6.0.0-1ubuntu2) lead to below compilation errors - 

./examples/daimler.c:23:18: error: expected ';' at end of declaration
        static float x_2 alignas(16) [36][18][4] = { 0 };
                        ^
                        ;
./examples/daimler.c:26:18: error: expected ';' at end of declaration
        static float x_5 alignas(16) [18][9][8] = { 0 };
                        ^
                        ;
./examples/daimler.c:29:18: error: expected ';' at end of declaration
        static float x_8 alignas(16) [9][4][16] = { 0 };
                        ^
                        ;
./examples/daimler.c:55:8: error: subscripted value is not an array, pointer, or vector
                                x_2[i_3 + 0][i_4 + 0][i_5 + 0] = b_0[i_5 + 0];
                                ~~~^~~~~~~~
./examples/daimler.c:69:39: error: subscripted value is not an array, pointer, or vector
                                                    x = _mm_load_ps((float*)&x_2[i_6 / 1 + 0][i_7 / 1 + 0][(i_59 * 1) % 4 + 0]);
                                                                             ~~~^~~~~~~~~~~~
./examples/daimler.c:71:36: error: subscripted value is not an array, pointer, or vector
                                                    _mm_store_ps((float*)&x_2[i_6 / 1 + 0][i_7 / 1 + 0][(i_59 * 1) % 4 + 0], x);
                                                                          ~~~^~~~~~~~~~~~
./examples/daimler.c:81:44: error: subscripted value is not an array, pointer, or vector
                                x_3[i_12 + 0][i_13 + 0][i_14 + 0] = x_2[i_12 + 0][i_13 + 0][i_14 + 0] < 0 ? 0 : x_2[i_12 + 0][i_13 + 0][i_14 + 0];
                                                                    ~~~^~~~~~~~~
./examples/daimler.c:81:88: error: subscripted value is not an array, pointer, or vector
                                x_3[i_12 + 0][i_13 + 0][i_14 + 0] = x_2[i_12 + 0][i_13 + 0][i_14 + 0] < 0 ? 0 : x_2[i_12 + 0][i_13 + 0][i_14 + 0];
                                                                                                                ~~~^~~~~~~~~
./examples/daimler.c:116:8: error: subscripted value is not an array, pointer, or vector
                                x_5[i_20 + 0][i_21 + 0][i_22 + 0] = b_1[i_22 + 0];
                                ~~~^~~~~~~~~
./examples/daimler.c:131:40: error: subscripted value is not an array, pointer, or vector
                                                            x = _mm_load_ps((float*)&x_5[i_23 / 1 + 0][i_24 / 1 + 0][i_28 + 0]);
                                                                                     ~~~^~~~~~~~~~~~~
./examples/daimler.c:133:37: error: subscripted value is not an array, pointer, or vector
                                                            _mm_store_ps((float*)&x_5[i_23 / 1 + 0][i_24 / 1 + 0][i_28 + 0], x);
                                                                                  ~~~^~~~~~~~~~~~~
./examples/daimler.c:144:44: error: subscripted value is not an array, pointer, or vector
                                x_6[i_29 + 0][i_30 + 0][i_31 + 0] = x_5[i_29 + 0][i_30 + 0][i_31 + 0] < 0 ? 0 : x_5[i_29 + 0][i_30 + 0][i_31 + 0];
                                                                    ~~~^~~~~~~~~
./examples/daimler.c:144:88: error: subscripted value is not an array, pointer, or vector
                                x_6[i_29 + 0][i_30 + 0][i_31 + 0] = x_5[i_29 + 0][i_30 + 0][i_31 + 0] < 0 ? 0 : x_5[i_29 + 0][i_30 + 0][i_31 + 0];
                                                                                                                ~~~^~~~~~~~~
./examples/daimler.c:179:8: error: subscripted value is not an array, pointer, or vector
                                x_8[i_37 + 0][i_38 + 0][i_39 + 0] = b_2[i_39 + 0];
                                ~~~^~~~~~~~~
./examples/daimler.c:194:40: error: subscripted value is not an array, pointer, or vector
                                                            x = _mm_load_ps((float*)&x_8[i_40 / 1 + 0][i_41 / 1 + 0][i_45 + 0]);
                                                                                     ~~~^~~~~~~~~~~~~
./examples/daimler.c:196:37: error: subscripted value is not an array, pointer, or vector
                                                            _mm_store_ps((float*)&x_8[i_40 / 1 + 0][i_41 / 1 + 0][i_45 + 0], x);
                                                                                  ~~~^~~~~~~~~~~~~
./examples/daimler.c:207:44: error: subscripted value is not an array, pointer, or vector
                                x_9[i_46 + 0][i_47 + 0][i_48 + 0] = x_8[i_46 + 0][i_47 + 0][i_48 + 0] < 0 ? 0 : x_8[i_46 + 0][i_47 + 0][i_48 + 0];
                                                                    ~~~^~~~~~~~~
./examples/daimler.c:207:88: error: subscripted value is not an array, pointer, or vector
                                x_9[i_46 + 0][i_47 + 0][i_48 + 0] = x_8[i_46 + 0][i_47 + 0][i_48 + 0] < 0 ? 0 : x_8[i_46 + 0][i_47 + 0][i_48 + 0];
                                                                                                                ~~~^~~~~~~~~
18 errors generated.

**Comment by OliverUrbann** [comment]
Thanks for reporting! No, "Unknown layer" should not happen here, the list of layers does not contain a layer that is not suppert. I will have a look at it.

**Comment by OliverUrbann** [comment]
Should be fixed now.

**Comment by gits00** [comment]
Thanks. It works now for SSE

General generator is failing
------------------------------------

Code change in applications/daimler/compile.py

general_generator = NNCG()
general_generator.keras_compile(images["images"], model, code_path, "qsse3", arch="sse3", testing=1000,
                                quatization=True, test_mode='classification')


#sse_generator = NNCG()
#sse_generator.keras_compile(images["images"], model, code_path, "sse3", arch="sse3", testing=1000)


Output

$ python3 applications/daimler/compile.py
Compiling |██████████████████████████████████------| 85.7% ./cnn_qsse3.cpp: In function ‘void cnnqsse3(float (*)[18][1], float*)’:
./cnn_qsse3.cpp:195:57: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ in assignment
     cx_0[i_89 + 0][i_90 + 0][i_91 + 0] = _mm_setzero_ps();
                                                         ^
Error compiling file with command:  g++ -mssse3 -std=c++11 -g -march=bonnell -DCNN_TEST ./cnn_qsse3.cpp -o ./cnn_qsse3


---------------------------------------------------------------
SSE generator is passing
------------------------

Code change in applications/daimler/compile.py

#general_generator = NNCG()
#general_generator.keras_compile(images["images"], model, code_path, "qsse3", arch="sse3", testing=1000,
#                                quatization=True, test_mode='classification')
sse_generator = NNCG()
sse_generator.keras_compile(images["images"], model, code_path, "sse3", arch="sse3", testing=1000)


python3 applications/daimler/compile.py
Finished |████████████████████████████████████████| 100.0% 7.1% ---| 0.0% 
Evaluating |████████████████████████████████████████| 100.0% , 100.0% ok, errors: ['0.000', '0.000', '0.000', '0.000', '0.000', '0.000', '0.000', '0.000']
Evaluating |████████████████████████████████████████| 100.1% , 100.0% ok, errors: ['0.000', '0.000', '0.000', '0.000', '0.000', '0.000', '0.000', '0.000']
Test finished.

------------------------------------------------------------

Both cpp are generated - 

ls *.cpp
cnn_qsse3.cpp  cnn_sse3.cpp

Only cnn_sse3.cpp is compiling via python code and creating the cnn_sse3 binary.

------------------------------------------------------------

Tried compiling cnn_qsse3.cpp using clang

clang -DCNN_TEST cnn_qsse3.cpp -o cnn_qsse3 -lm
cnn_qsse3.cpp:214:16: error: always_inline function '_mm_lddqu_si128' requires target feature 'sse3', but would be inlined into function 'cnnqsse3' that is compiled without support for 'sse3'
                                                            x = _mm_lddqu_si128((__m128i*)&x_14[i_37 + i_39][i_38 + i_40][i_41]);
                                                                ^
cnn_qsse3.cpp:215:16: error: always_inline function '_mm_lddqu_si128' requires target feature 'sse3', but would be inlined into function 'cnnqsse3' that is compiled without support for 'sse3'
                                                            w = _mm_lddqu_si128((__m128i*)&w_3[i_39][i_40][i_42][i_41]);
                                                                ^
cnn_qsse3.cpp:216:16: error: always_inline function '_mm_maddubs_epi16' requires target feature 'ssse3', but would be inlined into function 'cnnqsse3' that is compiled without support for 'ssse3'
                                                            x = _mm_maddubs_epi16(x, w);
                                                                ^
cnn_qsse3.cpp:230:14: error: always_inline function '_mm_hadd_epi32' requires target feature 'ssse3', but would be inlined into function 'cnnqsse3' that is compiled without support for 'ssse3'
                                sum1_0 = _mm_hadd_epi32(hi_0, lo_0);;
                                         ^
cnn_qsse3.cpp:231:14: error: always_inline function '_mm_hadd_epi32' requires target feature 'ssse3', but would be inlined into function 'cnnqsse3' that is compiled without support for 'ssse3'
                                sum2_0 = _mm_hadd_epi32(sum1_0, sum1_0);;
                                         ^
5 errors generated.

--------------------------------------------------------------------
Tried compiling cnn_sse3.cpp using g++ and clang individually - 
g++ -mssse3 -std=c++11 -g -march=bonnell -DCNN_TEST ./cnn_sse3.cpp -o ./cnn_sse3_with_gcc
clang -DCNN_TEST cnn_sse3.cpp -o cnn_sse3_with_clang -lm
this works and runs
-----------------------------------------------------------------------

Probabaly "general" generator/compiler is not finding it's dependencies but my Linux installation doesn't have them??

**Comment by OliverUrbann** [comment]
To sum up: cnn_qsse3.cpp cannot be compiled on you system at all (you tried g++ via python script and manually clang), cnn_sse3.cpp can be compile with g++ and clang?

**Comment by gits00** [comment]
OK, I see my mistake in compilation now. Here are the new results which you already confirmed. Just putting it out for reference.

$ g++ -mssse3 -std=c++11 -g -march=bonnell -DCNN_TEST ./cnn_qsse3.cpp -o ./cnn_qsse3 (FAILS)
./cnn_qsse3.cpp: In function ‘void cnnqsse3(float (*)[18][1], float*)’:
./cnn_qsse3.cpp:195:57: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ in assignment
     cx_0[i_89 + 0][i_90 + 0][i_91 + 0] = _mm_setzero_ps();

$ clang -mssse3 -std=c++11 -g -march=bonnell -DCNN_TEST ./cnn_qsse3.cpp -lm (COMPILES)



$ g++ -mssse3 -std=c++11 -g -march=bonnell -DCNN_TEST ./cnn_sse3.cpp -o ./cnn_sse3_with_gcc (COMPILES)
$ clang -DCNN_TEST cnn_sse3.cpp -o cnn_sse3_with_clang -lm (COMPILES)

Thanks again for fixing this. Up to 11.81 performance improvement due to this is quite impressive!
